apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "k8s.name" . }}-ingress
  labels:
    app: {{ include "k8s.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.hostname }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-service
