#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export PYTHONPATH=faustbr
export SIMPLE_SETTINGS=settings

${PREFIX}pytest ${1-"./tests"} ${2}
${PREFIX}black faustbr tests/ --check --diff
${PREFIX}flake8 faustbr tests/
